import type { FormTemplate } from "~/components/multi-step-form/types";

export const i765Template: FormTemplate = {
  id: "i-765",
  title: "Application for Employment Authorization",
  formNumber: "I-765",
  revision: "01/20/25",
  steps: [
    // Part 1: Reason for Applying
    {
      id: "part-1-reason",
      title: "Part 1. Reason for Applying",
      description: "Select the reason you are applying for an Employment Authorization Document (EAD).",
      fields: [
        {
          name: "reasonInitial",
          label: "Initial permission to accept employment",
          type: "checkbox",
          width: "1-1",
        },
        {
          name: "reasonReplacement",
          label: "Replacement of lost, stolen, or damaged employment authorization document, or correction of my employment authorization document NOT DUE to U.S. Citizenship and Immigration Services (USCIS) error",
          type: "checkbox",
          width: "1-1",
        },
        {
          name: "reasonRenewal",
          label: "Renewal of my permission to accept employment",
          helpText: "Attach a copy of your previous employment authorization document.",
          type: "checkbox",
          width: "1-1",
        },
      ],
    },
    // Part 2: Information About You - Legal Name
    {
      id: "part-2-legal-name",
      title: "Part 2. Your Full Legal Name",
      description: "Provide your full legal name as it appears on your immigration documents.",
      fields: [
        {
          name: "familyName",
          label: "Family Name (Last Name)",
          type: "text",
          width: "1-3",
          placeholder: "Enter your family name",
        },
        {
          name: "givenName",
          label: "Given Name (First Name)",
          type: "text",
          width: "1-3",
          placeholder: "Enter your given name",
        },
        {
          name: "middleName",
          label: "Middle Name",
          type: "text",
          width: "1-3",
          placeholder: "Enter your middle name",
        },
      ],
    },
    // Part 2: Other Names Used
    {
      id: "part-2-other-names",
      title: "Part 2. Other Names Used",
      description: "Provide all other names you have ever used, including aliases, maiden name, and nicknames.",
      helpText: "If you need extra space to complete this section, use the space provided in Part 6. Additional Information.",
      fields: [
        {
          name: "otherName1FamilyName",
          label: "Other Name 1 - Family Name (Last Name)",
          type: "text",
          width: "1-3",
        },
        {
          name: "otherName1GivenName",
          label: "Other Name 1 - Given Name (First Name)",
          type: "text",
          width: "1-3",
        },
        {
          name: "otherName1MiddleName",
          label: "Other Name 1 - Middle Name",
          type: "text",
          width: "1-3",
        },
        {
          name: "otherName2FamilyName",
          label: "Other Name 2 - Family Name (Last Name)",
          type: "text",
          width: "1-3",
        },
        {
          name: "otherName2GivenName",
          label: "Other Name 2 - Given Name (First Name)",
          type: "text",
          width: "1-3",
        },
        {
          name: "otherName2MiddleName",
          label: "Other Name 2 - Middle Name",
          type: "text",
          width: "1-3",
        },
        {
          name: "otherName3FamilyName",
          label: "Other Name 3 - Family Name (Last Name)",
          type: "text",
          width: "1-3",
        },
        {
          name: "otherName3GivenName",
          label: "Other Name 3 - Given Name (First Name)",
          type: "text",
          width: "1-3",
        },
        {
          name: "otherName3MiddleName",
          label: "Other Name 3 - Middle Name",
          type: "text",
          width: "1-3",
        },
      ],
    },
    // Part 2: Mailing Address
    {
      id: "part-2-mailing-address",
      title: "Part 2. Your U.S. Mailing Address",
      description: "Provide your current U.S. mailing address.",
      fields: [
        {
          name: "mailingInCareOf",
          label: "In Care Of Name (if any)",
          type: "text",
          width: "1-1",
          placeholder: "Enter name if applicable",
        },
        {
          name: "mailingStreet",
          label: "Street Number and Name",
          type: "text",
          width: "1-1",
          placeholder: "Enter street address",
        },
        {
          name: "mailingAptSteFlr",
          label: "Unit Type",
          type: "radio",
          options: [
            { value: "apt", label: "Apt." },
            { value: "ste", label: "Ste." },
            { value: "flr", label: "Flr." },
          ],
          width: "1-3",
        },
        {
          name: "mailingAptSteFlrNumber",
          label: "Unit Number",
          type: "text",
          width: "1-3",
          placeholder: "Unit #",
        },
        {
          name: "mailingCity",
          label: "City or Town",
          type: "text",
          width: "1-2",
          placeholder: "Enter city",
        },
        {
          name: "mailingState",
          label: "State",
          type: "select",
          options: [
            { value: "AL", label: "Alabama" },
            { value: "AK", label: "Alaska" },
            { value: "AZ", label: "Arizona" },
            { value: "AR", label: "Arkansas" },
            { value: "CA", label: "California" },
            { value: "CO", label: "Colorado" },
            { value: "CT", label: "Connecticut" },
            { value: "DE", label: "Delaware" },
            { value: "DC", label: "District of Columbia" },
            { value: "FL", label: "Florida" },
            { value: "GA", label: "Georgia" },
            { value: "HI", label: "Hawaii" },
            { value: "ID", label: "Idaho" },
            { value: "IL", label: "Illinois" },
            { value: "IN", label: "Indiana" },
            { value: "IA", label: "Iowa" },
            { value: "KS", label: "Kansas" },
            { value: "KY", label: "Kentucky" },
            { value: "LA", label: "Louisiana" },
            { value: "ME", label: "Maine" },
            { value: "MD", label: "Maryland" },
            { value: "MA", label: "Massachusetts" },
            { value: "MI", label: "Michigan" },
            { value: "MN", label: "Minnesota" },
            { value: "MS", label: "Mississippi" },
            { value: "MO", label: "Missouri" },
            { value: "MT", label: "Montana" },
            { value: "NE", label: "Nebraska" },
            { value: "NV", label: "Nevada" },
            { value: "NH", label: "New Hampshire" },
            { value: "NJ", label: "New Jersey" },
            { value: "NM", label: "New Mexico" },
            { value: "NY", label: "New York" },
            { value: "NC", label: "North Carolina" },
            { value: "ND", label: "North Dakota" },
            { value: "OH", label: "Ohio" },
            { value: "OK", label: "Oklahoma" },
            { value: "OR", label: "Oregon" },
            { value: "PA", label: "Pennsylvania" },
            { value: "RI", label: "Rhode Island" },
            { value: "SC", label: "South Carolina" },
            { value: "SD", label: "South Dakota" },
            { value: "TN", label: "Tennessee" },
            { value: "TX", label: "Texas" },
            { value: "UT", label: "Utah" },
            { value: "VT", label: "Vermont" },
            { value: "VA", label: "Virginia" },
            { value: "WA", label: "Washington" },
            { value: "WV", label: "West Virginia" },
            { value: "WI", label: "Wisconsin" },
            { value: "WY", label: "Wyoming" },
          ],
          width: "1-4",
          allowEmpty: true,
          emptyOptionLabel: "Select state",
        },
        {
          name: "mailingZipCode",
          label: "ZIP Code",
          type: "text",
          width: "1-4",
          placeholder: "ZIP",
        },
      ],
    },
    // Part 2: Physical Address
    {
      id: "part-2-physical-address",
      title: "Part 2. U.S. Physical Address",
      description: "Provide your physical address if different from your mailing address.",
      fields: [
        {
          name: "mailingAddressSameAsPhysical",
          label: "Is your current mailing address the same as your physical address?",
          type: "radio",
          options: [
            { value: "yes", label: "Yes" },
            { value: "no", label: "No" },
          ],
          width: "1-1",
        },
        {
          name: "physicalStreet",
          label: "Street Number and Name",
          type: "text",
          width: "1-1",
          showWhen: [
            { field: "mailingAddressSameAsPhysical", operator: "equals", value: "no" },
          ],
        },
        {
          name: "physicalAptSteFlr",
          label: "Unit Type",
          type: "radio",
          options: [
            { value: "apt", label: "Apt." },
            { value: "ste", label: "Ste." },
            { value: "flr", label: "Flr." },
          ],
          width: "1-3",
          showWhen: [
            { field: "mailingAddressSameAsPhysical", operator: "equals", value: "no" },
          ],
        },
        {
          name: "physicalAptSteFlrNumber",
          label: "Unit Number",
          type: "text",
          width: "1-3",
          showWhen: [
            { field: "mailingAddressSameAsPhysical", operator: "equals", value: "no" },
          ],
        },
        {
          name: "physicalCity",
          label: "City or Town",
          type: "text",
          width: "1-2",
          showWhen: [
            { field: "mailingAddressSameAsPhysical", operator: "equals", value: "no" },
          ],
        },
        {
          name: "physicalState",
          label: "State",
          type: "select",
          options: [
            { value: "AL", label: "Alabama" },
            { value: "AK", label: "Alaska" },
            { value: "AZ", label: "Arizona" },
            { value: "AR", label: "Arkansas" },
            { value: "CA", label: "California" },
            { value: "CO", label: "Colorado" },
            { value: "CT", label: "Connecticut" },
            { value: "DE", label: "Delaware" },
            { value: "DC", label: "District of Columbia" },
            { value: "FL", label: "Florida" },
            { value: "GA", label: "Georgia" },
            { value: "HI", label: "Hawaii" },
            { value: "ID", label: "Idaho" },
            { value: "IL", label: "Illinois" },
            { value: "IN", label: "Indiana" },
            { value: "IA", label: "Iowa" },
            { value: "KS", label: "Kansas" },
            { value: "KY", label: "Kentucky" },
            { value: "LA", label: "Louisiana" },
            { value: "ME", label: "Maine" },
            { value: "MD", label: "Maryland" },
            { value: "MA", label: "Massachusetts" },
            { value: "MI", label: "Michigan" },
            { value: "MN", label: "Minnesota" },
            { value: "MS", label: "Mississippi" },
            { value: "MO", label: "Missouri" },
            { value: "MT", label: "Montana" },
            { value: "NE", label: "Nebraska" },
            { value: "NV", label: "Nevada" },
            { value: "NH", label: "New Hampshire" },
            { value: "NJ", label: "New Jersey" },
            { value: "NM", label: "New Mexico" },
            { value: "NY", label: "New York" },
            { value: "NC", label: "North Carolina" },
            { value: "ND", label: "North Dakota" },
            { value: "OH", label: "Ohio" },
            { value: "OK", label: "Oklahoma" },
            { value: "OR", label: "Oregon" },
            { value: "PA", label: "Pennsylvania" },
            { value: "RI", label: "Rhode Island" },
            { value: "SC", label: "South Carolina" },
            { value: "SD", label: "South Dakota" },
            { value: "TN", label: "Tennessee" },
            { value: "TX", label: "Texas" },
            { value: "UT", label: "Utah" },
            { value: "VT", label: "Vermont" },
            { value: "VA", label: "Virginia" },
            { value: "WA", label: "Washington" },
            { value: "WV", label: "West Virginia" },
            { value: "WI", label: "Wisconsin" },
            { value: "WY", label: "Wyoming" },
          ],
          width: "1-4",
          allowEmpty: true,
          emptyOptionLabel: "Select state",
          showWhen: [
            { field: "mailingAddressSameAsPhysical", operator: "equals", value: "no" },
          ],
        },
        {
          name: "physicalZipCode",
          label: "ZIP Code",
          type: "text",
          width: "1-4",
          showWhen: [
            { field: "mailingAddressSameAsPhysical", operator: "equals", value: "no" },
          ],
        },
      ],
    },
    // Part 2: Other Information
    {
      id: "part-2-other-info",
      title: "Part 2. Other Information",
      description: "Provide additional identifying information.",
      fields: [
        {
          name: "alienNumber",
          label: "Alien Registration Number (A-Number) (if any)",
          helpText: "A-",
          type: "text",
          width: "1-2",
          placeholder: "Enter A-Number",
        },
        {
          name: "uscisOnlineAccountNumber",
          label: "USCIS Online Account Number (if any)",
          type: "text",
          width: "1-2",
          placeholder: "Enter account number",
        },
        {
          name: "sex",
          label: "Sex",
          type: "radio",
          options: [
            { value: "male", label: "Male" },
            { value: "female", label: "Female" },
          ],
          width: "1-2",
        },
        {
          name: "maritalStatus",
          label: "Marital Status",
          type: "radio",
          options: [
            { value: "single", label: "Single" },
            { value: "married", label: "Married" },
            { value: "divorced", label: "Divorced" },
            { value: "widowed", label: "Widowed" },
          ],
          width: "1-1",
        },
        {
          name: "previouslyFiledI765",
          label: "Have you previously filed Form I-765?",
          type: "radio",
          options: [
            { value: "yes", label: "Yes" },
            { value: "no", label: "No" },
          ],
          width: "1-1",
        },
      ],
    },
    // Part 2: Social Security Information
    {
      id: "part-2-ssn",
      title: "Part 2. Social Security Information",
      description: "Provide your Social Security information.",
      fields: [
        {
          name: "ssaIssuedCard",
          label: "Has the Social Security Administration (SSA) ever officially issued a Social Security card to you?",
          type: "radio",
          options: [
            { value: "yes", label: "Yes" },
            { value: "no", label: "No" },
          ],
          width: "1-1",
        },
        {
          name: "ssn",
          label: "Provide your Social Security number (SSN) (if known)",
          type: "text",
          width: "1-2",
          placeholder: "XXX-XX-XXXX",
          showWhen: [
            { field: "ssaIssuedCard", operator: "equals", value: "yes" },
          ],
        },
        {
          name: "wantSsnCard",
          label: "Do you want the SSA to issue you a Social Security card?",
          helpText: "You must also answer 'Yes' to Item Number 15., Consent for Disclosure, to receive a card.",
          type: "radio",
          options: [
            { value: "yes", label: "Yes" },
            { value: "no", label: "No" },
          ],
          width: "1-1",
        },
        {
          name: "consentForDisclosure",
          label: "Consent for Disclosure: I authorize disclosure of information from this application to the SSA as required for the purpose of assigning me an SSN and issuing me a Social Security card.",
          type: "radio",
          options: [
            { value: "yes", label: "Yes" },
            { value: "no", label: "No" },
          ],
          width: "1-1",
          showWhen: [
            { field: "wantSsnCard", operator: "equals", value: "yes" },
          ],
        },
      ],
    },
    // Part 2: Parent Information
    {
      id: "part-2-parents",
      title: "Part 2. Parent Information",
      description: "If you answered 'Yes' to requesting an SSN card, provide your parents' information.",
      helpText: "If you answered 'Yes' to Item Numbers 14. - 15., provide the information requested below.",
      fields: [
        {
          name: "fatherFamilyName",
          label: "Father's Family Name (Last Name)",
          helpText: "Provide your father's birth name.",
          type: "text",
          width: "1-2",
          showWhen: [
            { field: "wantSsnCard", operator: "equals", value: "yes" },
            { field: "consentForDisclosure", operator: "equals", value: "yes" },
          ],
        },
        {
          name: "fatherGivenName",
          label: "Father's Given Name (First Name)",
          type: "text",
          width: "1-2",
          showWhen: [
            { field: "wantSsnCard", operator: "equals", value: "yes" },
            { field: "consentForDisclosure", operator: "equals", value: "yes" },
          ],
        },
        {
          name: "motherFamilyName",
          label: "Mother's Family Name (Last Name)",
          helpText: "Provide your mother's birth name.",
          type: "text",
          width: "1-2",
          showWhen: [
            { field: "wantSsnCard", operator: "equals", value: "yes" },
            { field: "consentForDisclosure", operator: "equals", value: "yes" },
          ],
        },
        {
          name: "motherGivenName",
          label: "Mother's Given Name (First Name)",
          type: "text",
          width: "1-2",
          showWhen: [
            { field: "wantSsnCard", operator: "equals", value: "yes" },
            { field: "consentForDisclosure", operator: "equals", value: "yes" },
          ],
        },
      ],
    },
    // Part 2: Citizenship
    {
      id: "part-2-citizenship",
      title: "Part 2. Your Country or Countries of Citizenship or Nationality",
      description: "List all countries where you are currently a citizen or national.",
      helpText: "If you need extra space to complete this item, use the space provided in Part 6. Additional Information.",
      fields: [
        {
          name: "citizenshipCountry1",
          label: "Country of Citizenship 1",
          type: "text",
          width: "1-2",
          placeholder: "Enter country",
        },
        {
          name: "citizenshipCountry2",
          label: "Country of Citizenship 2",
          type: "text",
          width: "1-2",
          placeholder: "Enter country (if applicable)",
        },
      ],
    },
    // Part 2: Place of Birth
    {
      id: "part-2-birth",
      title: "Part 2. Place of Birth",
      description: "List the city/town/village, state/province, and country where you were born.",
      fields: [
        {
          name: "birthCity",
          label: "City/Town/Village of Birth",
          type: "text",
          width: "1-2",
          placeholder: "Enter city or town",
        },
        {
          name: "birthState",
          label: "State/Province of Birth",
          type: "text",
          width: "1-2",
          placeholder: "Enter state or province",
        },
        {
          name: "birthCountry",
          label: "Country of Birth",
          type: "text",
          width: "1-2",
          placeholder: "Enter country",
        },
        {
          name: "dateOfBirth",
          label: "Date of Birth (mm/dd/yyyy)",
          type: "date",
          width: "1-2",
        },
      ],
    },
    // Part 2: Last Arrival Information
    {
      id: "part-2-arrival",
      title: "Part 2. Information About Your Last Arrival in the United States",
      description: "Provide information about your most recent entry into the United States.",
      fields: [
        {
          name: "i94Number",
          label: "Form I-94 Arrival-Departure Record Number (if any)",
          type: "text",
          width: "1-1",
          placeholder: "Enter I-94 number",
        },
        {
          name: "passportNumber",
          label: "Passport Number of Your Most Recently Issued Passport",
          type: "text",
          width: "1-2",
          placeholder: "Enter passport number",
        },
        {
          name: "travelDocumentNumber",
          label: "Travel Document Number (if any)",
          type: "text",
          width: "1-2",
          placeholder: "Enter travel document number",
        },
        {
          name: "passportCountry",
          label: "Country That Issued Your Passport or Travel Document",
          type: "text",
          width: "1-2",
          placeholder: "Enter issuing country",
        },
        {
          name: "passportExpiration",
          label: "Expiration Date for Passport or Travel Document (mm/dd/yyyy)",
          type: "date",
          width: "1-2",
        },
        {
          name: "dateOfLastArrival",
          label: "Date of Your Last Arrival Into the United States, On or About (mm/dd/yyyy)",
          type: "date",
          width: "1-2",
        },
        {
          name: "placeOfLastArrival",
          label: "Place of Your Last Arrival Into the United States",
          type: "text",
          width: "1-2",
          placeholder: "Enter port of entry",
        },
        {
          name: "immigrationStatusAtArrival",
          label: "Immigration Status at Your Last Arrival (for example, B-2 visitor, F-1 student, or no status)",
          type: "text",
          width: "1-1",
          placeholder: "Enter immigration status",
        },
        {
          name: "currentImmigrationStatus",
          label: "Your Current Immigration Status or Category (for example, B-2 visitor, F-1 student, parolee, deferred action, or no status or category)",
          type: "text",
          width: "1-1",
          placeholder: "Enter current status",
        },
        {
          name: "sevisNumber",
          label: "Student and Exchange Visitor Information System (SEVIS) Number (if any)",
          helpText: "N-",
          type: "text",
          width: "1-2",
          placeholder: "Enter SEVIS number",
        },
      ],
    },
    // Part 2: Eligibility Category
    {
      id: "part-2-eligibility",
      title: "Part 2. Information About Your Eligibility Category",
      description: "Enter the appropriate eligibility category for this application.",
      helpText: "Refer to the Who May File Form I-765 section of the Form I-765 Instructions to determine the appropriate eligibility category for this application. Enter the appropriate letter and number for your eligibility category below (for example, (a)(8), (c)(17)(iii)).",
      fields: [
        {
          name: "eligibilityCategory",
          label: "Eligibility Category",
          type: "text",
          width: "1-1",
          placeholder: "e.g., (c)(9), (a)(8), (c)(3)(C)",
        },
        // STEM OPT Fields
        {
          name: "stemOptDegree",
          label: "(c)(3)(C) STEM OPT - Degree",
          type: "text",
          width: "1-1",
          showWhen: [
            { field: "eligibilityCategory", operator: "equals", value: "(c)(3)(C)" },
          ],
        },
        {
          name: "stemOptEmployerName",
          label: "(c)(3)(C) STEM OPT - Employer's Name as Listed in E-Verify",
          type: "text",
          width: "1-1",
          showWhen: [
            { field: "eligibilityCategory", operator: "equals", value: "(c)(3)(C)" },
          ],
        },
        {
          name: "stemOptEVerifyNumber",
          label: "(c)(3)(C) STEM OPT - Employer's E-Verify Company Identification Number or a Valid E-Verify Client Company Identification Number",
          type: "text",
          width: "1-1",
          showWhen: [
            { field: "eligibilityCategory", operator: "equals", value: "(c)(3)(C)" },
          ],
        },
        // (c)(26) Fields
        {
          name: "c26ReceiptNumber",
          label: "(c)(26) - Receipt Number of H-1B spouse's most recent Form I-797 Notice",
          type: "text",
          width: "1-1",
          showWhen: [
            { field: "eligibilityCategory", operator: "equals", value: "(c)(26)" },
          ],
        },
        // (c)(8) Fields
        {
          name: "c8ArrestedConvicted",
          label: "(c)(8) - Have you EVER been arrested for and/or convicted of any crime?",
          type: "radio",
          options: [
            { value: "yes", label: "Yes" },
            { value: "no", label: "No" },
          ],
          width: "1-1",
          showWhen: [
            { field: "eligibilityCategory", operator: "equals", value: "(c)(8)" },
          ],
        },
        // (c)(35)/(c)(36) Fields
        {
          name: "c35c36ReceiptNumber",
          label: "(c)(35)/(c)(36) - Receipt Number of Form I-797 Notice for Form I-140",
          type: "text",
          width: "1-1",
          showWhen: [
            { field: "eligibilityCategory", operator: "contains", value: "(c)(35)" },
          ],
        },
        {
          name: "c35c36ArrestedConvicted",
          label: "(c)(35)/(c)(36) - Have you EVER been arrested for and/or convicted of any crime?",
          type: "radio",
          options: [
            { value: "yes", label: "Yes" },
            { value: "no", label: "No" },
          ],
          width: "1-1",
          showWhen: [
            { field: "eligibilityCategory", operator: "contains", value: "(c)(35)" },
          ],
        },
      ],
    },
    // Part 3: Applicant's Statement
    {
      id: "part-3-statement",
      title: "Part 3. Applicant's Statement, Contact Information, Declaration, Certification, and Signature",
      description: "Provide your statement and contact information.",
      fields: [
        {
          name: "applicantCanReadEnglish",
          label: "I can read and understand English, and I have read and understand every question and instruction on this application and my answer to every question.",
          type: "checkbox",
          width: "1-1",
        },
        {
          name: "applicantUsedInterpreter",
          label: "The interpreter named in Part 4. read to me every question and instruction on this application and my answer to every question in a language in which I am fluent.",
          type: "checkbox",
          width: "1-1",
        },
        {
          name: "interpreterLanguage",
          label: "Language used by interpreter",
          type: "text",
          width: "1-2",
          showWhen: [
            { field: "applicantUsedInterpreter", operator: "equals", value: true },
          ],
        },
        {
          name: "applicantUsedPreparer",
          label: "At my request, the preparer named in Part 5., prepared this application for me based only upon information I provided or authorized.",
          type: "checkbox",
          width: "1-1",
        },
        {
          name: "applicantDaytimePhone",
          label: "Applicant's Daytime Telephone Number",
          type: "text",
          width: "1-2",
          placeholder: "(xxx) xxx-xxxx",
        },
        {
          name: "applicantMobilePhone",
          label: "Applicant's Mobile Telephone Number (if any)",
          type: "text",
          width: "1-2",
          placeholder: "(xxx) xxx-xxxx",
        },
        {
          name: "applicantEmail",
          label: "Applicant's Email Address (if any)",
          type: "text",
          width: "1-1",
          placeholder: "email@example.com",
        },
        {
          name: "abcSettlementEligible",
          label: "Select this box if you are a Salvadoran or Guatemalan national eligible for benefits under the ABC settlement agreement.",
          type: "checkbox",
          width: "1-1",
        },
      ],
    },
    // Part 4: Interpreter's Information
    {
      id: "part-4-interpreter",
      title: "Part 4. Interpreter's Contact Information, Certification, and Signature",
      description: "Provide information about the interpreter, if used.",
      fields: [
        {
          name: "interpreterFamilyName",
          label: "Interpreter's Family Name (Last Name)",
          type: "text",
          width: "1-2",
        },
        {
          name: "interpreterGivenName",
          label: "Interpreter's Given Name (First Name)",
          type: "text",
          width: "1-2",
        },
        {
          name: "interpreterBusinessName",
          label: "Interpreter's Business or Organization Name (if any)",
          type: "text",
          width: "1-1",
        },
        {
          name: "interpreterStreet",
          label: "Street Number and Name",
          type: "text",
          width: "1-1",
        },
        {
          name: "interpreterAptSteFlr",
          label: "Unit Type",
          type: "radio",
          options: [
            { value: "apt", label: "Apt." },
            { value: "ste", label: "Ste." },
            { value: "flr", label: "Flr." },
          ],
          width: "1-3",
        },
        {
          name: "interpreterAptSteFlrNumber",
          label: "Unit Number",
          type: "text",
          width: "1-3",
        },
        {
          name: "interpreterCity",
          label: "City or Town",
          type: "text",
          width: "1-2",
        },
        {
          name: "interpreterState",
          label: "State",
          type: "select",
          options: [
            { value: "AL", label: "Alabama" },
            { value: "AK", label: "Alaska" },
            { value: "AZ", label: "Arizona" },
            { value: "AR", label: "Arkansas" },
            { value: "CA", label: "California" },
            { value: "CO", label: "Colorado" },
            { value: "CT", label: "Connecticut" },
            { value: "DE", label: "Delaware" },
            { value: "DC", label: "District of Columbia" },
            { value: "FL", label: "Florida" },
            { value: "GA", label: "Georgia" },
            { value: "HI", label: "Hawaii" },
            { value: "ID", label: "Idaho" },
            { value: "IL", label: "Illinois" },
            { value: "IN", label: "Indiana" },
            { value: "IA", label: "Iowa" },
            { value: "KS", label: "Kansas" },
            { value: "KY", label: "Kentucky" },
            { value: "LA", label: "Louisiana" },
            { value: "ME", label: "Maine" },
            { value: "MD", label: "Maryland" },
            { value: "MA", label: "Massachusetts" },
            { value: "MI", label: "Michigan" },
            { value: "MN", label: "Minnesota" },
            { value: "MS", label: "Mississippi" },
            { value: "MO", label: "Missouri" },
            { value: "MT", label: "Montana" },
            { value: "NE", label: "Nebraska" },
            { value: "NV", label: "Nevada" },
            { value: "NH", label: "New Hampshire" },
            { value: "NJ", label: "New Jersey" },
            { value: "NM", label: "New Mexico" },
            { value: "NY", label: "New York" },
            { value: "NC", label: "North Carolina" },
            { value: "ND", label: "North Dakota" },
            { value: "OH", label: "Ohio" },
            { value: "OK", label: "Oklahoma" },
            { value: "OR", label: "Oregon" },
            { value: "PA", label: "Pennsylvania" },
            { value: "RI", label: "Rhode Island" },
            { value: "SC", label: "South Carolina" },
            { value: "SD", label: "South Dakota" },
            { value: "TN", label: "Tennessee" },
            { value: "TX", label: "Texas" },
            { value: "UT", label: "Utah" },
            { value: "VT", label: "Vermont" },
            { value: "VA", label: "Virginia" },
            { value: "WA", label: "Washington" },
            { value: "WV", label: "West Virginia" },
            { value: "WI", label: "Wisconsin" },
            { value: "WY", label: "Wyoming" },
          ],
          width: "1-4",
          allowEmpty: true,
          emptyOptionLabel: "Select state",
        },
        {
          name: "interpreterZipCode",
          label: "ZIP Code",
          type: "text",
          width: "1-4",
        },
        {
          name: "interpreterProvince",
          label: "Province",
          type: "text",
          width: "1-3",
        },
        {
          name: "interpreterPostalCode",
          label: "Postal Code",
          type: "text",
          width: "1-3",
        },
        {
          name: "interpreterCountry",
          label: "Country",
          type: "text",
          width: "1-3",
        },
        {
          name: "interpreterDaytimePhone",
          label: "Interpreter's Daytime Telephone Number",
          type: "text",
          width: "1-2",
        },
        {
          name: "interpreterMobilePhone",
          label: "Interpreter's Mobile Telephone Number (if any)",
          type: "text",
          width: "1-2",
        },
        {
          name: "interpreterEmail",
          label: "Interpreter's Email Address (if any)",
          type: "text",
          width: "1-1",
        },
        {
          name: "interpreterFluentLanguage",
          label: "I am fluent in English and the following language",
          helpText: "which is the same language specified in Part 3., Item Number 1.b.",
          type: "text",
          width: "1-1",
        },
      ],
    },
    // Part 5: Preparer's Information
    {
      id: "part-5-preparer",
      title: "Part 5. Contact Information, Declaration, and Signature of the Person Preparing this Application",
      description: "Provide information about the preparer, if other than the applicant.",
      fields: [
        {
          name: "preparerFamilyName",
          label: "Preparer's Family Name (Last Name)",
          type: "text",
          width: "1-2",
        },
        {
          name: "preparerGivenName",
          label: "Preparer's Given Name (First Name)",
          type: "text",
          width: "1-2",
        },
        {
          name: "preparerBusinessName",
          label: "Preparer's Business or Organization Name (if any)",
          type: "text",
          width: "1-1",
        },
        {
          name: "preparerStreet",
          label: "Street Number and Name",
          type: "text",
          width: "1-1",
        },
        {
          name: "preparerAptSteFlr",
          label: "Unit Type",
          type: "radio",
          options: [
            { value: "apt", label: "Apt." },
            { value: "ste", label: "Ste." },
            { value: "flr", label: "Flr." },
          ],
          width: "1-3",
        },
        {
          name: "preparerAptSteFlrNumber",
          label: "Unit Number",
          type: "text",
          width: "1-3",
        },
        {
          name: "preparerCity",
          label: "City or Town",
          type: "text",
          width: "1-2",
        },
        {
          name: "preparerState",
          label: "State",
          type: "select",
          options: [
            { value: "AL", label: "Alabama" },
            { value: "AK", label: "Alaska" },
            { value: "AZ", label: "Arizona" },
            { value: "AR", label: "Arkansas" },
            { value: "CA", label: "California" },
            { value: "CO", label: "Colorado" },
            { value: "CT", label: "Connecticut" },
            { value: "DE", label: "Delaware" },
            { value: "DC", label: "District of Columbia" },
            { value: "FL", label: "Florida" },
            { value: "GA", label: "Georgia" },
            { value: "HI", label: "Hawaii" },
            { value: "ID", label: "Idaho" },
            { value: "IL", label: "Illinois" },
            { value: "IN", label: "Indiana" },
            { value: "IA", label: "Iowa" },
            { value: "KS", label: "Kansas" },
            { value: "KY", label: "Kentucky" },
            { value: "LA", label: "Louisiana" },
            { value: "ME", label: "Maine" },
            { value: "MD", label: "Maryland" },
            { value: "MA", label: "Massachusetts" },
            { value: "MI", label: "Michigan" },
            { value: "MN", label: "Minnesota" },
            { value: "MS", label: "Mississippi" },
            { value: "MO", label: "Missouri" },
            { value: "MT", label: "Montana" },
            { value: "NE", label: "Nebraska" },
            { value: "NV", label: "Nevada" },
            { value: "NH", label: "New Hampshire" },
            { value: "NJ", label: "New Jersey" },
            { value: "NM", label: "New Mexico" },
            { value: "NY", label: "New York" },
            { value: "NC", label: "North Carolina" },
            { value: "ND", label: "North Dakota" },
            { value: "OH", label: "Ohio" },
            { value: "OK", label: "Oklahoma" },
            { value: "OR", label: "Oregon" },
            { value: "PA", label: "Pennsylvania" },
            { value: "RI", label: "Rhode Island" },
            { value: "SC", label: "South Carolina" },
            { value: "SD", label: "South Dakota" },
            { value: "TN", label: "Tennessee" },
            { value: "TX", label: "Texas" },
            { value: "UT", label: "Utah" },
            { value: "VT", label: "Vermont" },
            { value: "VA", label: "Virginia" },
            { value: "WA", label: "Washington" },
            { value: "WV", label: "West Virginia" },
            { value: "WI", label: "Wisconsin" },
            { value: "WY", label: "Wyoming" },
          ],
          width: "1-4",
          allowEmpty: true,
          emptyOptionLabel: "Select state",
        },
        {
          name: "preparerZipCode",
          label: "ZIP Code",
          type: "text",
          width: "1-4",
        },
        {
          name: "preparerProvince",
          label: "Province",
          type: "text",
          width: "1-3",
        },
        {
          name: "preparerPostalCode",
          label: "Postal Code",
          type: "text",
          width: "1-3",
        },
        {
          name: "preparerCountry",
          label: "Country",
          type: "text",
          width: "1-3",
        },
        {
          name: "preparerDaytimePhone",
          label: "Preparer's Daytime Telephone Number",
          type: "text",
          width: "1-2",
        },
        {
          name: "preparerMobilePhone",
          label: "Preparer's Mobile Telephone Number (if any)",
          type: "text",
          width: "1-2",
        },
        {
          name: "preparerEmail",
          label: "Preparer's Email Address (if any)",
          type: "text",
          width: "1-1",
        },
        {
          name: "preparerNotAttorney",
          label: "I am not an attorney or accredited representative but have prepared this application on behalf of the applicant and with the applicant's consent.",
          type: "checkbox",
          width: "1-1",
        },
        {
          name: "preparerIsAttorney",
          label: "I am an attorney or accredited representative and my representation of the applicant in this case",
          type: "checkbox",
          width: "1-1",
        },
        {
          name: "preparerRepresentationExtends",
          label: "extends beyond the preparation of this application",
          type: "checkbox",
          width: "1-2",
          showWhen: [
            { field: "preparerIsAttorney", operator: "equals", value: true },
          ],
        },
        {
          name: "preparerRepresentationDoesNotExtend",
          label: "does not extend beyond the preparation of this application",
          type: "checkbox",
          width: "1-2",
          showWhen: [
            { field: "preparerIsAttorney", operator: "equals", value: true },
          ],
        },
      ],
    },
    // Part 6: Additional Information
    {
      id: "part-6-additional",
      title: "Part 6. Additional Information",
      description: "If you need extra space to provide any additional information within this application, use the space below.",
      fields: [
        {
          name: "additionalFamilyName",
          label: "Family Name (Last Name)",
          type: "text",
          width: "1-3",
        },
        {
          name: "additionalGivenName",
          label: "Given Name (First Name)",
          type: "text",
          width: "1-3",
        },
        {
          name: "additionalMiddleName",
          label: "Middle Name",
          type: "text",
          width: "1-3",
        },
        {
          name: "additionalANumber",
          label: "A-Number (if any)",
          helpText: "A-",
          type: "text",
          width: "1-2",
        },
        // Additional Response 1
        {
          name: "additional1PageNumber",
          label: "Page Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional1PartNumber",
          label: "Part Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional1ItemNumber",
          label: "Item Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional1Response",
          label: "Additional Response",
          type: "textarea",
          rows: 6,
          width: "1-1",
        },
        // Additional Response 2
        {
          name: "additional2PageNumber",
          label: "Page Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional2PartNumber",
          label: "Part Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional2ItemNumber",
          label: "Item Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional2Response",
          label: "Additional Response",
          type: "textarea",
          rows: 6,
          width: "1-1",
        },
        // Additional Response 3
        {
          name: "additional3PageNumber",
          label: "Page Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional3PartNumber",
          label: "Part Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional3ItemNumber",
          label: "Item Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional3Response",
          label: "Additional Response",
          type: "textarea",
          rows: 6,
          width: "1-1",
        },
        // Additional Response 4
        {
          name: "additional4PageNumber",
          label: "Page Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional4PartNumber",
          label: "Part Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional4ItemNumber",
          label: "Item Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional4Response",
          label: "Additional Response",
          type: "textarea",
          rows: 6,
          width: "1-1",
        },
        // Additional Response 5
        {
          name: "additional5PageNumber",
          label: "Page Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional5PartNumber",
          label: "Part Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional5ItemNumber",
          label: "Item Number",
          type: "text",
          width: "1-4",
        },
        {
          name: "additional5Response",
          label: "Additional Response",
          type: "textarea",
          rows: 6,
          width: "1-1",
        },
      ],
    },
  ],

  // PDF Field Mappings - Maps form field names to PDF internal field names
  pdfFieldMappings: {
    // Part 1: Reason for Applying
    reasonInitial: "form1[0].Page1[0].Part1[0].Line1a_Checkbox[0]",
    reasonReplacement: "form1[0].Page1[0].Part1[0].Line1b_Checkbox[0]",
    reasonRenewal: "form1[0].Page1[0].Part1[0].Line1c_Checkbox[0]",

    // Part 2: Legal Name
    familyName: "form1[0].Page1[0].Part2[0].Line1a_FamilyName[0]",
    givenName: "form1[0].Page1[0].Part2[0].Line1b_GivenName[0]",
    middleName: "form1[0].Page1[0].Part2[0].Line1c_MiddleName[0]",

    // Part 2: Other Names
    otherName1FamilyName: "form1[0].Page1[0].Part2[0].Line2a_FamilyName[0]",
    otherName1GivenName: "form1[0].Page1[0].Part2[0].Line2b_GivenName[0]",
    otherName1MiddleName: "form1[0].Page1[0].Part2[0].Line2c_MiddleName[0]",
    otherName2FamilyName: "form1[0].Page1[0].Part2[0].Line3a_FamilyName[0]",
    otherName2GivenName: "form1[0].Page1[0].Part2[0].Line3b_GivenName[0]",
    otherName2MiddleName: "form1[0].Page1[0].Part2[0].Line3c_MiddleName[0]",
    otherName3FamilyName: "form1[0].Page1[0].Part2[0].Line4a_FamilyName[0]",
    otherName3GivenName: "form1[0].Page1[0].Part2[0].Line4b_GivenName[0]",
    otherName3MiddleName: "form1[0].Page1[0].Part2[0].Line4c_MiddleName[0]",

    // Part 2: Mailing Address
    mailingInCareOf: "form1[0].Page2[0].Part2[0].Line5a_InCareOf[0]",
    mailingStreet: "form1[0].Page2[0].Part2[0].Line5b_StreetNumberName[0]",
    "mailingAptSteFlr:apt": "form1[0].Page2[0].Part2[0].Line5c_Apt[0]",
    "mailingAptSteFlr:ste": "form1[0].Page2[0].Part2[0].Line5c_Ste[0]",
    "mailingAptSteFlr:flr": "form1[0].Page2[0].Part2[0].Line5c_Flr[0]",
    mailingAptSteFlrNumber: "form1[0].Page2[0].Part2[0].Line5c_AptSteFlrNumber[0]",
    mailingCity: "form1[0].Page2[0].Part2[0].Line5d_CityOrTown[0]",
    mailingState: "form1[0].Page2[0].Part2[0].Line5e_State[0]",
    mailingZipCode: "form1[0].Page2[0].Part2[0].Line5f_ZipCode[0]",

    // Part 2: Physical Address
    "mailingAddressSameAsPhysical:yes": "form1[0].Page2[0].Part2[0].Line6_Yes[0]",
    "mailingAddressSameAsPhysical:no": "form1[0].Page2[0].Part2[0].Line6_No[0]",
    physicalStreet: "form1[0].Page2[0].Part2[0].Line7a_StreetNumberName[0]",
    "physicalAptSteFlr:apt": "form1[0].Page2[0].Part2[0].Line7b_Apt[0]",
    "physicalAptSteFlr:ste": "form1[0].Page2[0].Part2[0].Line7b_Ste[0]",
    "physicalAptSteFlr:flr": "form1[0].Page2[0].Part2[0].Line7b_Flr[0]",
    physicalAptSteFlrNumber: "form1[0].Page2[0].Part2[0].Line7b_AptSteFlrNumber[0]",
    physicalCity: "form1[0].Page2[0].Part2[0].Line7c_CityOrTown[0]",
    physicalState: "form1[0].Page2[0].Part2[0].Line7d_State[0]",
    physicalZipCode: "form1[0].Page2[0].Part2[0].Line7e_ZipCode[0]",

    // Part 2: Other Info
    alienNumber: "form1[0].Page2[0].Part2[0].Line8_AlienNumber[0]",
    uscisOnlineAccountNumber: "form1[0].Page2[0].Part2[0].Line9_USCISOnlineAccountNumber[0]",
    "sex:male": "form1[0].Page2[0].Part2[0].Line10_Male[0]",
    "sex:female": "form1[0].Page2[0].Part2[0].Line10_Female[0]",
    "maritalStatus:single": "form1[0].Page2[0].Part2[0].Line11_Single[0]",
    "maritalStatus:married": "form1[0].Page2[0].Part2[0].Line11_Married[0]",
    "maritalStatus:divorced": "form1[0].Page2[0].Part2[0].Line11_Divorced[0]",
    "maritalStatus:widowed": "form1[0].Page2[0].Part2[0].Line11_Widowed[0]",
    "previouslyFiledI765:yes": "form1[0].Page2[0].Part2[0].Line12_Yes[0]",
    "previouslyFiledI765:no": "form1[0].Page2[0].Part2[0].Line12_No[0]",

    // Part 2: SSN Information
    "ssaIssuedCard:yes": "form1[0].Page2[0].Part2[0].Line13a_Yes[0]",
    "ssaIssuedCard:no": "form1[0].Page2[0].Part2[0].Line13a_No[0]",
    ssn: "form1[0].Page2[0].Part2[0].Line13b_SSN[0]",
    "wantSsnCard:yes": "form1[0].Page2[0].Part2[0].Line14_Yes[0]",
    "wantSsnCard:no": "form1[0].Page2[0].Part2[0].Line14_No[0]",
    "consentForDisclosure:yes": "form1[0].Page2[0].Part2[0].Line15_Yes[0]",
    "consentForDisclosure:no": "form1[0].Page2[0].Part2[0].Line15_No[0]",

    // Part 2: Parent Information
    fatherFamilyName: "form1[0].Page2[0].Part2[0].Line16a_FatherFamilyName[0]",
    fatherGivenName: "form1[0].Page2[0].Part2[0].Line16b_FatherGivenName[0]",
    motherFamilyName: "form1[0].Page2[0].Part2[0].Line17a_MotherFamilyName[0]",
    motherGivenName: "form1[0].Page2[0].Part2[0].Line17b_MotherGivenName[0]",

    // Part 2: Citizenship
    citizenshipCountry1: "form1[0].Page2[0].Part2[0].Line18a_Country[0]",
    citizenshipCountry2: "form1[0].Page2[0].Part2[0].Line18b_Country[0]",

    // Part 2: Birth Information
    birthCity: "form1[0].Page3[0].Part2[0].Line19a_CityTownVillage[0]",
    birthState: "form1[0].Page3[0].Part2[0].Line19b_StateProvince[0]",
    birthCountry: "form1[0].Page3[0].Part2[0].Line19c_Country[0]",
    dateOfBirth: "form1[0].Page3[0].Part2[0].Line20_DateOfBirth[0]",

    // Part 2: Arrival Information
    i94Number: "form1[0].Page3[0].Part2[0].Line21a_I94Number[0]",
    passportNumber: "form1[0].Page3[0].Part2[0].Line21b_PassportNumber[0]",
    travelDocumentNumber: "form1[0].Page3[0].Part2[0].Line21c_TravelDocNumber[0]",
    passportCountry: "form1[0].Page3[0].Part2[0].Line21d_PassportCountry[0]",
    passportExpiration: "form1[0].Page3[0].Part2[0].Line21e_PassportExpDate[0]",
    dateOfLastArrival: "form1[0].Page3[0].Part2[0].Line22_DateOfLastArrival[0]",
    placeOfLastArrival: "form1[0].Page3[0].Part2[0].Line23_PlaceOfLastArrival[0]",
    immigrationStatusAtArrival: "form1[0].Page3[0].Part2[0].Line24_ImmigrationStatusAtArrival[0]",
    currentImmigrationStatus: "form1[0].Page3[0].Part2[0].Line25_CurrentImmigrationStatus[0]",
    sevisNumber: "form1[0].Page3[0].Part2[0].Line26_SEVISNumber[0]",

    // Part 2: Eligibility Category
    eligibilityCategory: "form1[0].Page3[0].Part2[0].Line27_EligibilityCategory[0]",
    stemOptDegree: "form1[0].Page3[0].Part2[0].Line28a_Degree[0]",
    stemOptEmployerName: "form1[0].Page3[0].Part2[0].Line28b_EmployerName[0]",
    stemOptEVerifyNumber: "form1[0].Page3[0].Part2[0].Line28c_EVerifyNumber[0]",
    c26ReceiptNumber: "form1[0].Page3[0].Part2[0].Line29_ReceiptNumber[0]",
    "c8ArrestedConvicted:yes": "form1[0].Page3[0].Part2[0].Line30_Yes[0]",
    "c8ArrestedConvicted:no": "form1[0].Page3[0].Part2[0].Line30_No[0]",
    c35c36ReceiptNumber: "form1[0].Page3[0].Part2[0].Line31a_ReceiptNumber[0]",
    "c35c36ArrestedConvicted:yes": "form1[0].Page3[0].Part2[0].Line31b_Yes[0]",
    "c35c36ArrestedConvicted:no": "form1[0].Page3[0].Part2[0].Line31b_No[0]",

    // Part 3: Applicant's Statement
    applicantCanReadEnglish: "form1[0].Page4[0].Part3[0].Line1a_Checkbox[0]",
    applicantUsedInterpreter: "form1[0].Page4[0].Part3[0].Line1b_Checkbox[0]",
    interpreterLanguage: "form1[0].Page4[0].Part3[0].Line1b_Language[0]",
    applicantUsedPreparer: "form1[0].Page4[0].Part3[0].Line2_Checkbox[0]",
    applicantDaytimePhone: "form1[0].Page4[0].Part3[0].Line3_DaytimePhone[0]",
    applicantMobilePhone: "form1[0].Page4[0].Part3[0].Line4_MobilePhone[0]",
    applicantEmail: "form1[0].Page4[0].Part3[0].Line5_Email[0]",
    abcSettlementEligible: "form1[0].Page4[0].Part3[0].Line6_Checkbox[0]",

    // Part 4: Interpreter Information
    interpreterFamilyName: "form1[0].Page4[0].Part4[0].Line1a_FamilyName[0]",
    interpreterGivenName: "form1[0].Page4[0].Part4[0].Line1b_GivenName[0]",
    interpreterBusinessName: "form1[0].Page4[0].Part4[0].Line2_BusinessName[0]",
    interpreterStreet: "form1[0].Page5[0].Part4[0].Line3a_StreetNumberName[0]",
    "interpreterAptSteFlr:apt": "form1[0].Page5[0].Part4[0].Line3b_Apt[0]",
    "interpreterAptSteFlr:ste": "form1[0].Page5[0].Part4[0].Line3b_Ste[0]",
    "interpreterAptSteFlr:flr": "form1[0].Page5[0].Part4[0].Line3b_Flr[0]",
    interpreterAptSteFlrNumber: "form1[0].Page5[0].Part4[0].Line3b_Number[0]",
    interpreterCity: "form1[0].Page5[0].Part4[0].Line3c_CityOrTown[0]",
    interpreterState: "form1[0].Page5[0].Part4[0].Line3d_State[0]",
    interpreterZipCode: "form1[0].Page5[0].Part4[0].Line3e_ZipCode[0]",
    interpreterProvince: "form1[0].Page5[0].Part4[0].Line3f_Province[0]",
    interpreterPostalCode: "form1[0].Page5[0].Part4[0].Line3g_PostalCode[0]",
    interpreterCountry: "form1[0].Page5[0].Part4[0].Line3h_Country[0]",
    interpreterDaytimePhone: "form1[0].Page5[0].Part4[0].Line4_DaytimePhone[0]",
    interpreterMobilePhone: "form1[0].Page5[0].Part4[0].Line5_MobilePhone[0]",
    interpreterEmail: "form1[0].Page5[0].Part4[0].Line6_Email[0]",
    interpreterFluentLanguage: "form1[0].Page5[0].Part4[0].Cert_Language[0]",

    // Part 5: Preparer Information
    preparerFamilyName: "form1[0].Page5[0].Part5[0].Line1a_FamilyName[0]",
    preparerGivenName: "form1[0].Page5[0].Part5[0].Line1b_GivenName[0]",
    preparerBusinessName: "form1[0].Page5[0].Part5[0].Line2_BusinessName[0]",
    preparerStreet: "form1[0].Page5[0].Part5[0].Line3a_StreetNumberName[0]",
    "preparerAptSteFlr:apt": "form1[0].Page5[0].Part5[0].Line3b_Apt[0]",
    "preparerAptSteFlr:ste": "form1[0].Page5[0].Part5[0].Line3b_Ste[0]",
    "preparerAptSteFlr:flr": "form1[0].Page5[0].Part5[0].Line3b_Flr[0]",
    preparerAptSteFlrNumber: "form1[0].Page5[0].Part5[0].Line3b_Number[0]",
    preparerCity: "form1[0].Page5[0].Part5[0].Line3c_CityOrTown[0]",
    preparerState: "form1[0].Page5[0].Part5[0].Line3d_State[0]",
    preparerZipCode: "form1[0].Page5[0].Part5[0].Line3e_ZipCode[0]",
    preparerProvince: "form1[0].Page5[0].Part5[0].Line3f_Province[0]",
    preparerPostalCode: "form1[0].Page5[0].Part5[0].Line3g_PostalCode[0]",
    preparerCountry: "form1[0].Page5[0].Part5[0].Line3h_Country[0]",
    preparerDaytimePhone: "form1[0].Page5[0].Part5[0].Line4_DaytimePhone[0]",
    preparerMobilePhone: "form1[0].Page5[0].Part5[0].Line5_MobilePhone[0]",
    preparerEmail: "form1[0].Page5[0].Part5[0].Line6_Email[0]",
    preparerNotAttorney: "form1[0].Page6[0].Part5[0].Line7a_Checkbox[0]",
    preparerIsAttorney: "form1[0].Page6[0].Part5[0].Line7b_Checkbox[0]",
    preparerRepresentationExtends: "form1[0].Page6[0].Part5[0].Line7b_Extends[0]",
    preparerRepresentationDoesNotExtend: "form1[0].Page6[0].Part5[0].Line7b_DoesNotExtend[0]",

    // Part 6: Additional Information
    additionalFamilyName: "form1[0].Page7[0].Part6[0].Line1a_FamilyName[0]",
    additionalGivenName: "form1[0].Page7[0].Part6[0].Line1b_GivenName[0]",
    additionalMiddleName: "form1[0].Page7[0].Part6[0].Line1c_MiddleName[0]",
    additionalANumber: "form1[0].Page7[0].Part6[0].Line2_ANumber[0]",
    additional1PageNumber: "form1[0].Page7[0].Part6[0].Line3a_PageNumber[0]",
    additional1PartNumber: "form1[0].Page7[0].Part6[0].Line3b_PartNumber[0]",
    additional1ItemNumber: "form1[0].Page7[0].Part6[0].Line3c_ItemNumber[0]",
    additional1Response: "form1[0].Page7[0].Part6[0].Line3d_Response[0]",
    additional2PageNumber: "form1[0].Page7[0].Part6[0].Line4a_PageNumber[0]",
    additional2PartNumber: "form1[0].Page7[0].Part6[0].Line4b_PartNumber[0]",
    additional2ItemNumber: "form1[0].Page7[0].Part6[0].Line4c_ItemNumber[0]",
    additional2Response: "form1[0].Page7[0].Part6[0].Line4d_Response[0]",
    additional3PageNumber: "form1[0].Page7[0].Part6[0].Line5a_PageNumber[0]",
    additional3PartNumber: "form1[0].Page7[0].Part6[0].Line5b_PartNumber[0]",
    additional3ItemNumber: "form1[0].Page7[0].Part6[0].Line5c_ItemNumber[0]",
    additional3Response: "form1[0].Page7[0].Part6[0].Line5d_Response[0]",
    additional4PageNumber: "form1[0].Page7[0].Part6[0].Line6a_PageNumber[0]",
    additional4PartNumber: "form1[0].Page7[0].Part6[0].Line6b_PartNumber[0]",
    additional4ItemNumber: "form1[0].Page7[0].Part6[0].Line6c_ItemNumber[0]",
    additional4Response: "form1[0].Page7[0].Part6[0].Line6d_Response[0]",
    additional5PageNumber: "form1[0].Page7[0].Part6[0].Line7a_PageNumber[0]",
    additional5PartNumber: "form1[0].Page7[0].Part6[0].Line7b_PartNumber[0]",
    additional5ItemNumber: "form1[0].Page7[0].Part6[0].Line7c_ItemNumber[0]",
    additional5Response: "form1[0].Page7[0].Part6[0].Line7d_Response[0]",
  },

  // Autofill Mappings - Maps form field names to canonical client data fields
  // Note: Fields like alienNumber, uscisOnlineAccountNumber, ssn, and birthCountry
  // are not mapped because they don't have corresponding canonical fields yet.
  // These can be added to shared/src/canonicalFields.ts if autofill is needed.
  autofillMappings: {
    familyName: "last_name",
    givenName: "first_name",
    middleName: "middle_name",
    sex: "gender",
    citizenshipCountry1: "nationality",
    birthCity: "place_of_birth",
    dateOfBirth: "date_of_birth",
    i94Number: "i94_number",
    passportNumber: "passport_number",
    passportCountry: "passport_issuing_country",
    passportExpiration: "passport_expiry_date",
    travelDocumentNumber: "travel_document_number",
    dateOfLastArrival: "i94_admission_date",
    immigrationStatusAtArrival: "i94_class_of_admission",
  },
};

export default i765Template;
